sudo: false

language: scala

services:
  - docker

jdk:
  - openjdk8
  - openjdk11

scala:
  - 2.12.10

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION build
