sudo: false

language: scala

services:
  - docker

jdk:
  - openjdk8
  - openjdk12

scala:
  - 2.12.10

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION build

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION publish
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v
